version: '3.8'

services:
  node:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mongo
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/myapp

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
